version: '3'

services:
  nextjs:
    build:
      context: . 
      dockerfile: Dockerfile # The single Dockerfile for both Nginx and Next.js
    environment:
      - PORT=5006
    expose:
      - '5006'  # Internal communication with Nginx
    networks:
      - app_network

  nginx:
    build:
      context: . 
      dockerfile: Dockerfile # Same Dockerfile but Nginx will serve the proxy
    ports:
      - '5005:5005'  # Expose port 5005 externally for Nginx
    depends_on:
      - nextjs
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
