version: '3'

services:
  # Next.js App
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    expose:
      - "5006"  # Exposes port 3000 to other services in the same network
    networks:
      - nextjs-network

  # Nginx (reverse proxy)
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"  # Exposes Nginx on port 80 for public access
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Copy your custom Nginx config
    depends_on:
      - nextjs  # Ensures Nginx starts after Next.js app
    networks:
      - nextjs-network

networks:
  nextjs-network:
    driver: bridge
