version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      container-name: nextjs
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - nextjs
    hostname: nextjs 

  nginx:
    image: nginx:latest
    container-name: nextjs-nginx
    ports:
      - "5006:5006"
    volumes:
      - ./default.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nextjs

networks:
  nextjs:
    driver: bridge
