
services:
  ims-nextjs:
    container_name: ims-nextjs
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    volumes:
      - .:/app
      - /app/node_modules
      - ./src:/app/src 
      #- /etc/ssl/certs:/etc/ssl/certs         # Mount /etc/ssl/certs
      #- /etc/ssl/private:/etc/ssl/private 
    stdin_open: true
    tty: true
    networks:
      - nextjs
  
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      #- /etc/ssl/certs:/etc/ssl/certs         # Mount /etc/ssl/certs
      #- /etc/ssl/private:/etc/ssl/private  # Mount NGINX config
    ports:
      - "5005:5005"  # Expose port 80 for incoming traffic
    networks:
      - nextjs
networks:
  nextjs:
    driver: bridge
