
services:
  ims-nextjs:
    container_name: ims-nextjs
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    volumes:
      - .:/app
      - /app/node_modules
      - ./src:/app/src 
      - /etc/ssl/certs:/etc/ssl/certs         # Mount /etc/ssl/certs
      - /etc/ssl/private:/etc/ssl/private 
    stdin_open: true
    tty: true
