
services:
  nextjs:
    container_name: nextjs
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5006:5006"
    volumes:
      - .:/app
      - /app/node_modules
      - ./src:/app/src 
    stdin_open: true
    tty: true
