version: '3'
services:
  nextjs:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - nextjs
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5005:5005'
    depends_on:
      - nextjs
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nextjs

networks:
  nextjs:
    driver: bridge