version: "3.7"

services:
  nextjs-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-prod
    ports:
      - "5005:5005"  # Map container port 5005 to host port 5005
    environment:
      - NODE_ENV=production
