version: "3.7"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-docker-nextjs-dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "5005:5005"