
services:
  ims-nextjs:
    container_name: ims-nextjs
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - ./src:/app/src 
      #- /etc/ssl/certs:/etc/ssl/certs         # Mount /etc/ssl/certs
      #- /etc/ssl/private:/etc/ssl/private 
    stdin_open: true
    tty: true
    expose:
      - 5005
    networks:
      - nextjs
  
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf  # Mount Nginx configuration file only
      - ./public:/app/public                          # Static public folder
      - ./next.config.js:/app/next.config.js          # Optionally mount the Next.js config if needed
    ports:
      - "80:5005"  # Map Nginx port to 80
    networks:
      - nextjs

networks:
  nextjs:
    driver: bridge
