version: '3'
services:
  nextjs:
    build: .
    ports:
      - '5005:5005'
    volumes:
      - ./:/app
      - /app/node_modules
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '50005:5005'
    depends_on:
      - nextjs
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf