version: '3'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=5006
    expose:
      - '5006'
    networks:
      - app_network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5005:5005' # External access to Nginx
    depends_on:
      - nextjs
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
