version: '3.8'

services:
  app:
    build: .
    container_name: nextjs-app
    ports:
      - "5006:5006"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    networks:
      - nextjs_network
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "5006:5006"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nextjs_network

networks:
  nextjs_network:
    driver: bridge
