version: '3'

services:
  # NestJS service 1
  nestjs-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5006:5006"  # Expose 3001 externally, 3000 internally
    volumes:
      - .:/app
      - ./src:/app/src 
    networks:
      - backend
    deploy:
      replicas: 3

  # NGINX service for load balancing
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/certs:/etc/ssl/certs         # Mount /etc/ssl/certs
      - /etc/ssl/private:/etc/ssl/private  # Mount NGINX config
    ports:
      - "5006:5006"  # Expose port 80 for incoming traffic
    networks:
      - backend

networks:
  backend:
    driver: bridge
