name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Git
      - name: Set up Git
        run: |
          git config user.name "jenecilpatac"
          git config user.email "jenecilpatac@gmail.com"

      # Step 3: Check for Modified Files
      - name: Detect Changes
        run: |
          if git diff-index --quiet HEAD --; then
            echo "No changes detected. Exiting workflow."
            exit 0
          fi

      # Step 4: Commit changes
      - name: Commit Changes
        run: |
          git add .
          git commit -m "Auto commit: updated files"

      # Step 5: Push Changes to the Repository
      - name: Push Changes
        run: |
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
