name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Git
      - name: Set up Git
        run: |
          git config user.name "jenecilpatac"
          git config user.email "jenecilpatac@gmail.com"

      # Step 3: Commit the changes
      - name: Commit changes
        run: |
          git add .
          git commit -m "Auto commit: update the file with new changes" || echo "No changes to commit"
        continue-on-error: true  # Prevent failure if no changes exist

      # Step 4: Push changes to the repository
      - name: Push changes
        run: |
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
