name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use your Node.js version

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          npm install -g pnpm
          pnpm install

      # Step 4: Lint the code
      - name: Run Lint
        run: pnpm run lint


      # Step 5: Build the application
      - name: Build Application
        run: pnpm run build

      # # Step 5: Deploy the frontend to the server
      # - name: Deploy frontend to Server
      #   run: |
      #     echo "Deploying frontend..."
      #     ssh -i ${{ secrets.SSH_KEY }} user@your-server-ip "cd /path/to/client && git pull && npm run start"  # Deploy to server
      #   env:
      #     SSH_KEY: ${{ secrets.SSH_KEY }}  # Use SSH key for authentication
