name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up a compatible Node.js version (>=18)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Or use '20' if you prefer

      # Step 3: Install dependencies for the frontend (Next.js)
      - name: Install dependencies
        run: |
          cd client  # Go to your frontend directory (ensure the folder is named 'client')
          npm install  # Install frontend dependencies
          pnpm install

      # Step 4: Build the frontend (Next.js)
      - name: Build frontend
        run: |
          cd client
          pnpm run build  # Build the app

      # # Step 5: Deploy the frontend to the server
      # - name: Deploy frontend to Server
      #   run: |
      #     echo "Deploying frontend..."
      #     ssh -i ${{ secrets.SSH_KEY }} user@your-server-ip "cd /path/to/client && git pull && npm run start"  # Deploy to server
      #   env:
      #     SSH_KEY: ${{ secrets.SSH_KEY }}  # Use SSH key for authentication
