name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout your code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js for Next.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: |
          cd client  # Ensure you are in the correct directory
          npm install  # Install frontend dependencies

      # Build the frontend
      - name: Build frontend
        run: |
          cd client
          npm run build

      # Deploy frontend to server
      - name: Deploy frontend to Server
        run: |
          echo "Deploying frontend..."
          ssh -i ${{ secrets.SSH_KEY }} user@your-server-ip "cd /path/to/frontend && git pull && npm run start"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
