name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to main, can be adjusted to your preferred branch
  pull_request:
    branches:
      - main  # Trigger when a pull request is created targeting main

jobs:
  auto-commit-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Git
      - name: Set up Git
        run: |
          git config user.name "jenecil"
          git config user.email "jenecilpatac@gmail.com"

      # Step 3: Stage all changes (git add .)
      - name: Stage changes
        run: |
          git add .
        
      # Step 4: Commit changes (if any changes exist)
      - name: Commit changes
        run: |
          git commit -m "Auto commit: Changes made on $(date)" || echo "No changes to commit"

      # Step 5: Push changes back to the repository
      - name: Push changes to the repository
        run: |
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  


