name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Client Directory
        run: ls -la client/

      - name: Install pnpm
        run: npm install -g pnpm

      # Install dependencies in client/
      - name: Install Dependencies
        working-directory: client
        run: pnpm install

      # Build the project in client/
      - name: Build Next.js Project
        working-directory: client
        run: pnpm build

      # Upload artifact from client/out
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: client/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
