name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]  # Trigger when pushing to the main branch
  workflow_dispatch:  # Allow manual trigger from the GitHub UI

permissions:
  contents: read
  pages: write
  id-token: write  # Required for GitHub Pages deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        working-directory: client
        run: pnpm install

      - name: Build with Next.js
        working-directory: client
        run: pnpm build  # Generates the .next folder

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: client/.next  # Path to the build output directory

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}  # Output page URL after deployment
    runs-on: ubuntu-latest
    needs: build  # Ensure the build step is completed before deployment

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_id: ${{ steps.upload-artifact.outputs.artifact_id }}  # Pass the artifact ID
